"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TaskEscrow__factory = exports.MockERC20__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MockERC20__factory_1 = require("./MockERC20__factory");
Object.defineProperty(exports, "MockERC20__factory", { enumerable: true, get: function () { return MockERC20__factory_1.MockERC20__factory; } });
var TaskEscrow__factory_1 = require("./TaskEscrow__factory");
Object.defineProperty(exports, "TaskEscrow__factory", { enumerable: true, get: function () { return TaskEscrow__factory_1.TaskEscrow__factory; } });
